// Generated by CoffeeScript 1.6.3
(function() {
  var Task;

  exports.Task = Task = function(msg, ackFn) {
    this.id = msg.id;
    this.action = msg.action;
    this.src = msg.src;
    this.dest = msg.dest;
    this.params = msg.params;
    this.done = function() {
      return ackFn();
    };
    this.retry = function(timeout) {
      var fn;
      if (timeout == null) {
        timeout = 60;
      }
      fn = function() {
        return ackFn(false);
      };
      return setTimeout(fn, timeout * 1000);
    };
    return this;
  };

}).call(this);
